services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    producer:
        build: .
        depends_on:
            - kafka
        working_dir: /app
        command: python producer.py
        environment:
            KAFKA_BROKER: kafka:29092
    consumer:
        build: .
        depends_on:
            - kafka
        working_dir: /app
        command: python consumer.py
        environment:
            KAFKA_BROKER: kafka:29092