services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        healthcheck:
            test: echo ruok | nc localhost 2181 | grep imok || exit -1
            interval: 10s
            retries: 5
            timeout: 10s
        mem_limit: 384m
    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        depends_on:
            zookeeper:
                condition: service_healthy
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        healthcheck:
            test: kafka-topics.sh --bootstrap-server kafka:29092 --list || exit -1
            interval: 10s
            retries: 5
            timeout: 10s
        mem_limit: 1g
        restart: on-failure
    cassandra:
        build: 
            context: ./jmx_exporter
            dockerfile: Dockerfile
        ports:
            - "9042:9042"
            - "8080:8080"
        volumes:
            - cassandra-data:/var/lib/cassandra
        environment:
            MAX_HEAP_SIZE: 1024M
        healthcheck:
            test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
            interval: 20s
            timeout: 10s
            retries: 10
        mem_limit: 2.3g
    cassandra-init:
        image: cassandra:latest
        depends_on:
            cassandra: 
                condition: service_healthy
        volumes:
            - ./init.cql:/init.cql
        entrypoint: >
            bash -c "
                until cqlsh cassandra 9042 --request-timeout=60 -e 'DESCRIBE KEYSPACES'; do
                    echo 'Waiting for Cassandra to be ready...';
                    sleep 10;
                done;
                cqlsh cassandra 9042 --request-timeout=60 -f /init.cql
            "
    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: --config.file=/etc/prometheus/prometheus.yml
        depends_on:
            cassandra:
                condition: service_healthy
        mem_limit: 384m
        cpus: 1.0
    producer:
        build: .
        depends_on:
            kafka:
                condition: service_healthy
        working_dir: /app
        command: python producer.py
        environment:
            KAFKA_BROKER: kafka:29092
            KAFKA_TOPIC: vehicle_data
        deploy:
            replicas: 4
    consumer:
        build: .
        restart: always
        depends_on:
            kafka:
                condition: service_healthy
            cassandra-init:
                condition: service_completed_successfully
        working_dir: /app
        command: python consumer.py
        environment:
            KAFKA_BROKER: kafka:29092
            KAFKA_TOPIC: vehicle_data
volumes:
  cassandra-data: