services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
    kafka:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    timescaleDB:
        image: timescale/timescaledb:latest-pg16
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: vehicle_data
        ports:
            - "5432:5432"
        volumes:
            - ./init_timescaleDB.sql:/docker-entrypoint-initdb.d/init_timescaledb.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d vehicle_data"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
    producer:
        build: .
        depends_on:
            kafka:
                condition: service_started
            timescaleDB:
                condition: service_healthy
        working_dir: /app
        command: python producer.py
        environment:
            KAFKA_BROKER: kafka:29092
    consumer:
        build: .
        depends_on:
            kafka:
                condition: service_started
            timescaleDB:
                condition: service_healthy
        working_dir: /app
        command: python consumer.py
        environment:
            KAFKA_BROKER: kafka:29092
            TIMESCALEDB_HOST: timescaleDB
            TIMESCALEDB_PORT: 5432
            TIMESCALEDB_USER: postgres
            TIMESCALEDB_PASSWORD: password
            TIMESCALEDB_DB: vehicle_data